name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  version:
    uses: ./.github/workflows/template-compute-release-version.yml

  web:
    name: Deploy Web to Prod
    needs: version
    uses: ./.github/workflows/template-web-build-and-deploy.yml
    with:
      version: ${{ needs.version.outputs.version }}
      cloudflare_project_name: jufk-prod
    secrets: inherit

  ios:
    name: Deploy iOS to App Store
    needs: version
    uses: ./.github/workflows/template-ios-build-and-publish.yml
    with:
      destination: testflight_upload
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  android:
    name: Deploy Android to Production
    needs: version
    uses: ./.github/workflows/template-android-build-and-publish.yml
    with:
      destination: alpha
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  github-release:
    name: Create GitHub Release
    needs: [web, ios, android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
