name: Deploy Web to Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web:
    name: Deploy Web to Test
    uses: ./.github/workflows/template-web-build-and-deploy.yml
    with:
      cloudflare_project_name: jufk-test
    secrets: inherit
